
services:
  nginx:
    image: nginx
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wp_data:/var/www/html:ro
    env_file:
      - .env
    networks:
      - wp-net
    depends_on:
      - wordpress
  mariadb:
    image: mariadb
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    volumes:
      - wp_db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wp-net
  wordpress:
    image: wordpress
    build: requirements/wordpress/
    container_name: wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    networks:
      - wp-net
  redis:
      image: redis
      build: requirements/bonus/redis/
      networks:
        - wp-net
      container_name: redis
      restart: always
  static:
    image: static
    container_name: static
    build: requirements/bonus/static
    ports:
      - "3001:3001"
    restart: always
  adminer:
    image: adminer
    container_name: adminer
    build: requirements/bonus/adminer
    volumes:
      - wp_data:/var/www/html:rw
    networks:
      - wp-net
    depends_on:
      - wordpress
    restart: always

  vsftpd:
    image: vsftpd
    build: requirements/bonus/vsftpd/
    networks:
      - wp-net
    env_file:
      - .env
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wp_data:/var/www/html:rw
    container_name: vsftpd
    restart: always

  cadvisor:
    image: cadvisor
    build: requirements/bonus/cadvisor/
    networks:
      - wp-net
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    container_name: cadvisor
    restart: always



networks:
  wp-net:
    name: wp-net
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/maecarva/data/wp-files/'
  
  wp_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/maecarva/data/wp-db/'
