
services:
  nginx:
    image: nginx
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    volumes:
      - wp_data:/var/www/html:ro
    env_file:
      - .env
    networks:
      - wp-net
    depends_on:
      - wordpress
  mariadb:
    image: mariadb
    build: requirements/mariadb/
    container_name: mariadb
    restart: always
    volumes:
      - wp_db:/var/lib/mysql
    env_file:
      - .env
    networks:
      - wp-net
  wordpress:
    image: wordpress
    build: requirements/wordpress/
    container_name: wordpress
    restart: always
    volumes:
      - wp_data:/var/www/html
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    networks:
      - wp-net
  redis:
      image: redis
      build: requirements/bonus/redis/
      networks:
        - wp-net
      container_name: redis
      restart: always
  static:
    image: static
    build: requirements/bonus/static
    ports:
      - "3001:3001"
    restart: always
  adminer:
    image: adminer
    build: requirements/bonus/adminer
    volumes:
      - wp_data:/var/www/html
    networks:
      - wp-net
    depends_on:
      - wordpress
    restart: always



networks:
  wp-net:
    name: wp-net
    driver: bridge

volumes:
  wp_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/maecarva/data/wp-files/'
  
  wp_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/maecarva/data/wp-db/'
