SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$DB_ROOT_PASSWORD');

CREATE DATABASE IF NOT EXISTS inceptiondb;

GRANT ALL PRIVILEGES ON inceptiondb.* TO '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';

FLUSH PRIVILEGES;
