SET PASSWORD FOR 'root'@'localhost' = PASSWORD('$DB_ROOT_PASSWORD');

CREATE DATABASE IF NOT EXISTS inceptiondb;

CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';

GRANT ALL PRIVILEGES ON inceptiondb.* TO '$DB_USER'@'%';

FLUSH PRIVILEGES;
